# FROM ubuntu:22.04
# FROM nvidia/cuda:12.0.0-devel-ubuntu22.04
# https://catalog.ngc.nvidia.com/orgs/nvidia/containers/deepstream/tags
FROM nvcr.io/nvidia/deepstream:6.4-gc-triton-devel

ENV TZ="America/New_York"
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USERNAME=user

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all 

# ADD REQUIRED PACKAGES
RUN apt-get update && apt-get install -y \
    sudo \
    vim htop \
    libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev \
    xvfb x11-apps \
    curl build-essential \
    ca-certificates gnupg \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev \
    gstreamer1.0-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ADD LOCAL USER
# Step to check if the group exists and create it if it doesn't
RUN if getent group $GROUP_ID ; then echo "Group $GROUP_ID already exists"; else groupadd --gid $GROUP_ID $USERNAME; fi
# Always attempt to create the user, adding it to the existing or newly created group
# Check if the user exists and create it if it doesn't
RUN if getent passwd $USER_ID ; then \
        echo "User with UID $USER_ID already exists"; \
    else \
        useradd --uid $USER_ID --gid $GROUP_ID --create-home $USERNAME; \
    fi
RUN echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers; 
# RUN groupadd --gid $GROUP_ID $USERNAME && \
#     useradd --uid $USER_ID --gid $GROUP_ID \
#     $USERNAME && \
#     echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER $USERNAME
WORKDIR /home/$USERNAME

RUN sudo chmod 777 .

# RUST INSTALLATION
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.73.0 -y
ENV PATH="/home/$USERNAME/.cargo/bin:${PATH}"

# NODE/NPM INSTALLATION
RUN sudo mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN sudo apt-get update && sudo apt-get install nodejs -y

WORKDIR /home/$USERNAME/app