# FROM ubuntu:22.04
FROM nvidia/cuda:12.3.1-base-ubuntu22.04

ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USERNAME=user

# ADD REQUIRED PACKAGES
RUN apt-get update && apt-get install -y \
    sudo \
    vim htop \
    ffmpeg \
    libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev \
    xvfb x11-apps \
    curl build-essential \
    ca-certificates gnupg \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav libgstrtspserver-1.0-dev libges-1.0-dev \
    gstreamer1.0-tools \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# ADD LOCAL USER
RUN groupadd --gid $GROUP_ID $USERNAME && \
    useradd --uid $USER_ID --gid $GROUP_ID \
    $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER $USERNAME
WORKDIR /home/$USERNAME

RUN sudo chmod 777 .

# RUST INSTALLATION
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain 1.73.0 -y
ENV PATH="/home/$USERNAME/.cargo/bin:${PATH}"

# NODE/NPM INSTALLATION
RUN sudo mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
RUN sudo apt-get update && sudo apt-get install nodejs -y

# PYTHON KLVDATA INSTALLATION
RUN pip3 install klvdata
# RUN curl -fsSL https://bun.sh/install | bash 
# RUN echo 'alias bun=~/.bun/bin/bun' > ~/.bashrc

WORKDIR /home/$USERNAME/app